variables:
  IMAGE_NAME: "$CI_REGISTRY/$CI_PROJECT_PATH:$CI_COMMIT_SHORT_SHA"

stages:
  - build
  - test
  - deploy

build_job:
  stage: build
  before_script:
    - echo "$PASSWORD" | docker login -u "$USER" --password-stdin "$CI_REGISTRY"
  script:
    - echo "start build" 
  after_script:
    - echo "after build"
  tags:
    - local

test_job:
  stage: test
  before_script:
    - echo "before test"
  script:
    - echo "start test" 
  after_script:
    - echo "after test"
  tags:
    - local

deploy_job:
  stage: deploy
  before_script:
    - echo "before deploy"
  script:
    - echo "start deploy" 
  after_script:
    - echo "after deploy"
  tags:
    - local