variables:
  IMAGE_NAME: "$CI_REGISTRY/$CI_PROJECT_PATH:$CI_COMMIT_SHORT_SHA"
  DOCKERFILE_PATH: "docker/small.Dockerfile"

stages:
  - build
  - test
  - deploy

build_job:
  stage: build
  before_script:
    - echo "$PASSWORD" | docker login -u "$USER" --password-stdin "$CI_REGISTRY"
  script:
    - docker build -f "$DOCKERFILE_PATH" -t "$IMAGE_NAME" .
    - docker push "$IMAGE_NAME"
  after_script:
    - echo "after build"
  tags:
    - local

test_job:
  stage: test
  before_script:
    - echo "before test"
  script:
    - echo "start test" 
  after_script:
    - echo "after test"
  tags:
    - local

deploy_job:
  stage: deploy
  before_script:
    - echo "$PASSWORD" | docker login -u "$USER" --password-stdin "$CI_REGISTRY"
    - echo "IMAGE_NAME=$IMAGE_NAME" >> .env
  script:
    - docker compose pull tg-bot
    - docker compose up -d tg-bot
  after_script:
    - echo "after deploy"
  tags:
    - local